name: audio_env
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip=22.3.1
  - numpy=1.23.5
  - six
  - setuptools
  - wheel
  - cffi
  - libffi
  - pip:
    - appdirs==1.4.4
    - audioread==3.0.0
    - charset-normalizer==3.0.1
    - decorator==5.1.1
    - idna==3.4
    - joblib==1.2.0
    - librosa==0.9.2
    - llvmlite==0.39.1
    - numba==0.56.4
    - packaging==23.0
    - pooch==1.6.0
    - pycparser==2.21
    - requests==2.28.2
    - resampy==0.4.2
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - soundfile==0.11.0
    - threadpoolctl==3.1.0
    - urllib3==1.26.14
